### ISSUE TITLE
RemoteUpload & AjaxRequest

### ISSUE THREAD

**Issue by novashdima** [misterunknown/ifm#164] opened 2020-12-29 18:15 UTC
When opening this menus currenDir empty, so IFM change directory to root location.
So if I upload file throught this menus this files uploaded in root instead of current dir.

**Comment by misterunknown** [comment] 2020-12-30 05:52
Confirmed, seems to be an error in the template. These links shouldn't have a href attribute. I'll fix that when I merged your pull request.

**Comment by misterunknown** [comment] 2021-01-21 16:28
Is fixed in #164

**Closed by misterunknown** 2021-01-21 16:28 UTC
