### ISSUE TITLE
no preview picture with other root_dir

### ISSUE THREAD

**Issue by rocket-it** [misterunknown/ifm#84] opened 2017-12-08 19:42 UTC
If another root_dir than "" in ifm.php there is no preview picture or status line in browser
Tested with firefox 57 and chromium 62

**Comment by misterunknown** [comment] 2017-12-11 10:39
This is right. It was the intended behaviour till now, because the images could not be delivered via the webserver. Of course, I can deliver the images via the script itself, which I just implemented.

I'll merge this branch after the pending tests are completed.

**Comment by misterunknown** [comment] 2017-12-11 13:58
[Link to corresponding branch](https://github.com/misterunknown/ifm/tree/issue-84).

**Comment by misterunknown** [comment] 2017-12-15 15:11
Merged.

**Closed by misterunknown** 2017-12-15 15:11 UTC
