### ISSUE TITLE
Feature Request: Extract ZIP File

### ISSUE THREAD

**Issue by Concept211** [misterunknown/ifm#5] opened 2016-11-18 10:47 UTC
It would be great to have the ability to upload a .ZIP file and have IFM extract the contents to path of where it was uploaded to. Even better would be the option to ZIP up an entire directory or full root.

Thank you for your hard work on this amazing project!

**Comment by misterunknown** [comment] 2016-11-18 14:36
Well, you should already have the ability to extract zip files, as long as you didn't change the configuration. Just click the extract button in the last column. If you find any bugs please let me know ;)

**Comment by Concept211** [comment] 2016-11-18 15:30
Oh, man...how did I miss that?! Works perfectly, thank you! I guess the only thing that I would request is the ability to ZIP the entire path from the location of where IFM is currently located. Beneficial for backing up an entire site to move to a new server rather than FTPing files one by one.  I saw that you can zip+download entire directories, but you would still need to click on each one to get the entire root.

**Comment by misterunknown** [comment] 2016-11-18 15:39
Well, yes, that would be nice. I'll add this feature.

**Comment by Concept211** [comment] 2016-11-18 17:50
Thank you!!

**Comment by misterunknown** [comment] 2016-11-23 04:25
I added a button which allows you to download the current directory as a zip file. This button also works in the highest level, so you can download entire document roots. Please test this version and let me know if you find any bugs or flaws.

**Comment by misterunknown** [comment] 2016-11-29 13:56
I guess this can be closed.

**Comment by Concept211** [comment] 2016-11-29 14:20
Sorry for the delay! Thank you very much for adding this. I was trying to upload it to one of my client's sites who is hosted on GoDaddy, but for some reason the file never fully completes uploading. I've even tried uploading IFM compressed in a zip files and then uncompressing it directly on the server, but the script fails to run. I'm guessing it's due to its huge file size and there may be some limitations on GoDaddy's shared servers. Have you run into this issue before?

**Comment by misterunknown** [comment] 2016-11-29 14:33
No problem :) I never had this issue, but it may be related to some GoDaddy restrictions. Can you look into the PHP error logs on the server? Otherwise you can put the following lines at top of the script, so maybe it tells you what goes wrong:
```
<?php
error_reporting( E_ALL );
ini_set( 'display_errors', 'on' );

...
```

**Comment by Concept211** [comment] 2016-11-29 21:08
I don't get GoDaddy. When I try uploading the file it'll get to the end and then restart the upload over and over and never actually complete. They must have something strange going on in their security settings. I'll just need to write my own lightweight solution at some point to quickly zip/unzip files directly on the server.

As for your update. I tried running it on a different host and all works fine when zipping the root, but for some reason when the zipping is completed, the page tries to download the file "root.zip" but saves an empty 1kb file. But if you refresh or check the FTP, you see the temp file with the .zip extension, but it still has the temp file name. See screenshot below. Not a deal breaker, but just something I figured you'd want to know about.

![snap137](https://cloud.githubusercontent.com/assets/589002/20728787/54411096-b64d-11e6-9b0d-92cd7676d2d6.png)

**Comment by misterunknown** [comment] 2016-11-30 08:24
Thanks for your feedback. During the development I also had problems with 1kb archives. Can you open this 1kb file with an text editor and look if it contains an error message? Does this error occur on all your systems or only on a specific one?

**Comment by Concept211** [comment] 2016-11-30 18:04
Yes, actually it does:

`<br />
<b>Fatal error</b>:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 690278400 bytes) in <b>/path/path/path/ifm.php</b> on line <b>1654</b><br />
`

**Comment by misterunknown** [comment] 2016-11-30 21:28
Well, this should not happen normally. The function I call when a directory is zipped and downloaded is "readfile". This function is not expected to load the whole file into the memory. Maybe output_buffering is activated in PHP. Maybe it is more stable to rely on the webserver for serving this file. I'll try to patch that ;)

**Comment by misterunknown** [comment] 2016-11-30 22:41
I created a separate branch with a possible fix for this issue: https://github.com/misterunknown/ifm/tree/issue5
Please test it and let me know if that helps ;) Thanks for your participation! :+1:

**Comment by Concept211** [comment] 2016-12-01 09:22
Unfortunately, root.zip error again:
`<br />
<b>Warning</b>:  file_put_contents(/var/www/sites/test.misterunknown.de/tmp/phplog): failed to open stream: No such file or directory in <b>/path/path/ifm.php</b> on line <b>1663</b><br />
<br />
<b>Fatal error</b>:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 689889280 bytes) in <b>/path/path/ifm.php</b> on line <b>1665</b><br />
`

Looks like you hardcoded the temp path though:
**/var/www/sites/test.misterunknown.de/tmp/phplog**

**Comment by misterunknown** [comment] 2016-12-01 09:27
Well, what a shame^^ I forgot to remove two temporary debug outputs. I just updated the branch again. Now it should work.

**Comment by misterunknown** [comment] 2016-12-01 09:37
If it does not work yet, could you provide an anonymized phpinfo() output to me? Then I can try to reproduce the error by using your php configuration.

**Comment by Concept211** [comment] 2016-12-01 09:49
Same error:
`<br />
<b>Fatal error</b>:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 689889280 bytes) in <b>/path/path/ifm.php</b> on line <b>1663</b><br />
`
Any way to PM or email so that I can send you the phpinfo()?

**Comment by misterunknown** [comment] 2016-12-01 10:04
Of course, just send it to marco@misterunknown.de.

**Comment by misterunknown** [comment] 2016-12-01 16:29
Thanks for your mail. I could not really identify, what the problem is. I first assumed that the error occured due to output_buffering, but obviously this is deactivated on your server.

So I simply wrote a different download function, which I could test successfully in different setups (even with little memory_limits). Please take a look. I commited it to the issue5 branch: https://github.com/misterunknown/ifm/commit/e1a575e4f87d94b271a85b5311bc98055917698b

**Comment by Concept211** [comment] 2016-12-01 17:06
Hmm...close. This time it downloads a large root.zip file:
![image](https://cloud.githubusercontent.com/assets/589002/20803161/400d18e8-b7bc-11e6-9ec6-934177962b87.png)

But when you open it, it throws an archive error:
![image](https://cloud.githubusercontent.com/assets/589002/20803181/4f00f36a-b7bc-11e6-8cd2-2773b6d09053.png)

And on the server, the temp file name still exists. If you download that file instead, the zip opens/extracts just fine:
![image](https://cloud.githubusercontent.com/assets/589002/20803229/71f12e80-b7bc-11e6-93e2-52abd14225b7.png)

I noticed both files are of different size. Almost like the final chunk of data didn't get saved before streaming out the file to the browser:
![image](https://cloud.githubusercontent.com/assets/589002/20803836/9760f306-b7be-11e6-9632-3853e37dd632.png)

**Comment by Concept211** [comment] 2016-12-01 17:09
I just noticed that the original file size while downloading was correct, but when it finished the size changed which is odd.

**Comment by Concept211** [comment] 2016-12-01 17:17
Nevermind! I tried one more time and this time it worked perfectly. It even deleted the temp file from the server. Thanks!
![image](https://cloud.githubusercontent.com/assets/589002/20804251/2e63266a-b7c0-11e6-93ff-2969f34036e3.png)

**Comment by misterunknown** [comment] 2016-12-02 09:27
I'm glad that it works for you now :+1: 

Yes, the IFM should normally delete the temporary zip files after the download is completed. Of course this can't be done if a fatal error occurs.

I merged the branch issue5 to master and deleted the branch.

**Closed by misterunknown** 2016-12-02 09:27 UTC
