### ISSUE TITLE
Picture previews won’t close

### ISSUE THREAD

**Issue by maggie44** [misterunknown/ifm#162] opened 2020-12-28 23:25 UTC
When using the demo, if you click an image when using a smart phone it try’s to load a hovering preview even though it takes you directly to the clicked link. Then the hovering images get stuck on top of the interface. 

Hard to know what a solution or expected behaviour should be. When a mobile loads it ideally it disables the image preview? If a phone loads it as a desktop website though, presumably it would still be an issue. 

Testing with Safari on an iPhone 12 mini. 

![23844CB9-75FC-4A2F-B39B-C50E66DA1CD1](https://user-images.githubusercontent.com/64841595/103248698-0f0e1500-4929-11eb-8cea-531259ab9c4f.jpeg)
![4295F1C1-C5CE-4E02-9CDF-88E5A8A64112](https://user-images.githubusercontent.com/64841595/103248702-11706f00-4929-11eb-81cd-e7ffa15e5d91.jpeg)
![77F3BAAA-4C32-4A9F-998A-7154014B31DB](https://user-images.githubusercontent.com/64841595/103248703-12090580-4929-11eb-8442-07507479a796.jpeg)
![856FE99C-2ADE-4181-8DD7-2ADAE750F420](https://user-images.githubusercontent.com/64841595/103248704-12a19c00-4929-11eb-940d-a00aa3a91d7f.jpeg)

**Comment by novashdima** [comment] 2020-12-29 17:20
Hi, @maggie0002.
On my mobile chrome if I click on picture I get this picture as new web page without popover.
I try to disable  popover on mobile, check my changes in pull request #161.

**Comment by misterunknown** [comment] 2020-12-30 05:55
I can't confirm that, since I have no iphone; on android there is no preview. But I guess the pull request from @novashdima (#161) should solve that.

**Comment by maggie0002** [comment] 2021-01-01 02:31
> Hi, @maggie0002.
> On my mobile chrome if I click on picture I get this picture as new web page without popover.
> I try to disable popover on mobile, check my changes in pull request #161.

Checked it with that pull request and has resolved the issue. Only tested on iPhone 12 mini using Safari, but think it's safe to assume it will be ok now for other iPhones too. Tested it loading the page which defaults to the 'mobile version', then requested Safari fetch the 'desktop version' of the website, which also appears to be problem free. 

Thanks.

**Comment by maggie0002** [comment] 2021-01-28 01:30
I just discovered that this is happening occasionally on the desktop too. Using Safari I occasionally find images stuck on the screen. You can navigate in and out of folders and it remains there the whole time until you refresh the page. Not sure how to reproduce it exactly, but clicking around in and out of folders and files while intermittently hovering to display a picture and it occurs (in Safari at least). 

Not sure what to suggest, as for mobile it was decided just to disable it rather than try and fix it. Perhaps worth considering whether this feature brings any significant benefit, it may be more trouble that its worth? I see value in being able to preview files, but perhaps a thumbnail view as an alternative to the last view would be more valuable anyway. 

<img width="1327" alt="Screenshot 2021-01-27 at 17 25 34" src="https://user-images.githubusercontent.com/64841595/106076736-03974080-60c5-11eb-96fd-6440e48bf8e3.png">
<img width="1340" alt="Screenshot 2021-01-27 at 17 25 56" src="https://user-images.githubusercontent.com/64841595/106076744-07c35e00-60c5-11eb-9c06-591b5ff10b33.png">

**Comment by misterunknown** [comment] 2023-12-05 14:51
I couldn't replicate that in Safari, so for now I'd close this issue.

**Closed by misterunknown** 2023-12-05 14:51 UTC
