### ISSUE TITLE
Cannot browse subfolders or open files

### ISSUE THREAD

**Issue by swurzinger** [misterunknown/ifm#45] opened 2017-07-17 12:57 UTC
When clicking on a folder in the list the folder's contents are not shown. Instead, when clicking e.g. a folder "System" the URL changes to http://<site>#ystem and the textbox at the top shows "ystem" too. This looks like the first character is stripped off.

Hardlinks and symbolic links to folders are not handled correctly and are shown as if they were files.

Trying to open / edit a file results in a 404 error (when clicking on the name) or the error "This file can not be displayed or edited." (when using the "edit" button).  The Download button works.

PHP 7.0 on Windows NT 10.0 AMD64

IFM 2.4.1 from https://github.com/misterunknown/ifm/archive/v2.4.1.zip  (internal VERSION constant says 2.4.0, though)

**Comment by misterunknown** [comment] 2017-07-17 13:16
Thanks for your feedback. I'll take a look on this asap.

**Comment by misterunknown** [comment] 2017-07-17 14:25
I just tested the current IFM version with a Windows Server 2012 and PHP 7 and couldn't reproduce your error. Please provide the following information:
* Did you set a custom `root_dir`?
* Are there any error messages in the javascript console? (F12->Console for most browsers)
* Are there any errors in the PHP error.log?
* Please send me the output of one api function. To do so, follow these steps:
  * Open the IFM and go to the ajax request dialog (press <kbd>a</kbd> or open it via the menu)
  * Enter in the "data" textbox the following: ```api=getFiles```, let the URL field free
  * Press "Request" and provide the output which should appear in the response textarea

Thanks in advance!

**Comment by swurzinger** [comment] 2017-07-17 15:30
Thanks for your response.

1. Yes I did. I tried both "D:\\" and "D:/" and the error occurs either way. However the problem seems to be related to the custom root_dir being the drive root as navigating into a subfolder works with other root dirs or without setting a root dir at all.
2. No messages in the console
3. No errors in the error log

`[{"name":"$Recycle.Bin","type":"dir","icon":"icon icon-folder-empty","lastmodified":"11.03.2016, 0:08 UTC","size":"0 Byte"},{"name":"$WINDOWS.~BT","type":"dir","icon":"icon icon-folder-empty","lastmodified":"13.07.2017, 20:05 UTC","size":"4 KB"},{"name":"ekey","type":"dir","icon":"icon icon-folder-empty","lastmodified":"06.04.2016, 17:06 UTC","size":"0 Byte"},{"name":"Intel","type":"dir","icon":"icon icon-folder-empty","lastmodified":"04.03.2016, 0:25 UTC","size":"0 Byte"},{"name":"MinGW","type":"dir","icon":"icon icon-folder-empty","lastmodified":"05.03.2016, 21:39 UTC","size":"0 Byte"},{"name":"Msys","type":"dir","icon":"icon icon-folder-empty","lastmodified":"05.03.2016, 20:44 UTC","size":"4 KB"},{"name":"PerfLogs","type":"dir","icon":"icon icon-folder-empty","lastmodified":"16.07.2016, 11:47 UTC","size":"0 Byte"},{"name":"Program Files","type":"dir","icon":"icon icon-folder-empty","lastmodified":"14.06.2017, 13:18 UTC","size":"12 KB"},{"name":"Program Files (x86)","type":"dir","icon":"icon icon-folder-empty","lastmodified":"29.04.2017, 21:49 UTC","size":"12 KB"},{"name":"ProgramData","type":"dir","icon":"icon icon-folder-empty","lastmodified":"17.11.2016, 9:52 UTC","size":"8 KB"},{"name":"ramdi","type":"dir","icon":"icon icon-folder-empty","lastmodified":"26.03.2016, 0:54 UTC","size":"0 Byte"},{"name":"Recovery","type":"dir","icon":"icon icon-folder-empty","lastmodified":"22.09.2016, 2:14 UTC","size":"0 Byte"},{"name":"System Volume Information","type":"dir","icon":"icon icon-folder-empty","lastmodified":"17.02.2017, 7:31 UTC","size":"4 KB"},{"name":"Users","type":"dir","icon":"icon icon-folder-empty","lastmodified":"22.09.2016, 2:07 UTC","size":"4 KB"},{"name":"Windows","type":"dir","icon":"icon icon-folder-empty","lastmodified":"17.07.2017, 11:09 UTC","size":"24 KB"},{"name":"bootmgr","type":"file","icon":"icon icon-doc","lastmodified":"30.10.2015, 7:18 UTC","size":"390.85 KB"},{"name":"BOOTNXT","type":"file","icon":"icon icon-doc","lastmodified":"30.10.2015, 7:18 UTC","size":"1 Byte"},{"name":"Dokumente und Einstellungen","type":"file","icon":"icon icon-doc","lastmodified":"01.01.1970, 0:00 UTC","size":" Byte"},{"name":"hiberfil.sys","type":"file","icon":"icon icon-doc","lastmodified":"01.01.1970, 0:00 UTC","size":" Byte"},{"name":"pagefile.sys","type":"file","icon":"icon icon-doc","lastmodified":"01.01.1970, 0:00 UTC","size":" Byte"},{"name":"Programme","type":"file","icon":"icon icon-doc","lastmodified":"01.01.1970, 0:00 UTC","size":" Byte"},{"name":"ramdisk","type":"file","icon":"icon icon-doc","lastmodified":"01.01.1970, 0:00 UTC","size":" Byte"},{"name":"swapfile.sys","type":"file","icon":"icon icon-doc","lastmodified":"01.01.1970, 0:00 UTC","size":" Byte"}]`

**Comment by misterunknown** [comment] 2017-07-17 18:16
Interesting. I'll take a look. I only tested the IFM on *nix systems, yet, so thank you for the hint.

**Comment by misterunknown** [comment] 2017-07-18 11:05
Well, I just pushed a patch which should fix the problem with changing the directory. I tested this under Windows 7/PHP7.0 and Windows Server 2012/PHP7.1.

Unfortunately I couldn't reproduce the malfunction of the edit function. To get further information I'd like you to follow these steps:
* install the latest IFM version from the master branch
* perform an ajax request with the following parameters (one parameter per line):
```
api=getContent
dir=<DIR>
filename=<FILENAME>
```
You have to replace `<DIR>` and `<FILENAME>` with correct values on your system.

**Comment by swurzinger** [comment] 2017-07-18 11:31
Thank you for the fix. I've merged your changes and it solved the directory navigation issue.

I've tried the following parameters for the request and got a "500 - Internal Server Error" response from the server. 
```
api=getContent
dir=Intel\Logs
filename=IntelGFX.log
```

PHP Error:
```
php[25144]
PHP Fatal error:  Uncaught Error: Call to undefined function mb_convert_encoding() in ifm.php:1815
Stack trace:
#0 ifm.php(1583): IFM->getContent(Array)
#1 ifm.php(1617): IFM->handleRequest()
#2 ifm.php(2837): IFM->run()
#3 {main}
  thrown in ifm.php on line 1815
```
Shall I create a new ticket for that?

**Comment by misterunknown** [comment] 2017-07-18 11:58
> Uncaught Error: Call to undefined function mb_convert_encoding()

This seems to indicate a missing PHP extension. Please check in your phpinfo() if you loaded the _mbstring_ module ([see also](http://php.net/manual/de/book.mbstring.php)).

**Comment by swurzinger** [comment] 2017-07-18 12:03
That solved the issue (see "//edit" in my previous comment).

**Comment by misterunknown** [comment] 2017-07-18 12:26
Ah nice. Yes, this should be either mentioned in the requirements.

I close this for now. Please let me know if you find any further bugs.

**Closed by misterunknown** 2017-07-18 12:26 UTC
